server:
  port: 8088
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    platform: MySQL
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/university?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123456
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL55Dialect
    #  open-in-view: false
    generate-ddl: true
