server:
  port: 8080

  spring:
    datasource:
      platform: MySQL
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/university
      username: root
      password: 123456

      #JPA properties

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL55Dialect
  generate-ddl: true

